const OPERACIONES_TAIR = {
  DIRECTORIO_LIMA: 7,
  AREQUIPA: 64,
  LIMA: 65,
  PENDIENTES: 86,
  VENDIDAS: 109,
  PERDIDAS: 162,
  AJENAS: 211,
  SUBCONTRATADAS: 238,
  DIRECTORIO_AREQ: 552
};

const TIPOS_DOC_REA = {
  ENTREGA: 1,
  DEVOLUCION: 2,
  VENTA: 3,
  TRASLADO: 4,
  PERDIDA: 5,
};

module.exports = { OPERACIONES_TAIR, TIPOS_DOC_REA };
