FROM node:18

RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    && rm -rf /var/lib/apt/lists/*

COPY docker/ibm-iaccess.deb /tmp/
WORKDIR /tmp

RUN dpkg -i ibm-iaccess.deb || true && \
    apt-get update && \
    apt-get install -f -y

RUN echo "[IBM i Access ODBC Driver]" > /etc/odbcinst.ini && \
    echo "Description=IBM i ODBC Driver" >> /etc/odbcinst.ini && \
    echo "Driver=/opt/ibm/iaccess/lib64/libcwbodbc.so" >> /etc/odbcinst.ini

WORKDIR /gescon-api

COPY package*.json ./
RUN npm install --legacy-peer-deps

# Instalar nodemon globalmente para hot reload
RUN npm install -g nodemon


EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "server.js"]